export const GET_HOTEL_EVENTS_START= 'GET_HOTEL_EVENTS_START';
export const GET_HOTEL_EVENTS_SUCCESS= 'GET_HOTEL_EVENTS_SUCCESS';
export const GET_HOTEL_EVENTS_ERROR = 'GET_HOTEL_EVENTS_ERROR';

export const GET_ARRIVED_THIS_WEEK_START = 'GET_ARRIVED_THIS_WEEK_START';
export const GET_ARRIVED_THIS_WEEK_SUCCESS = 'GET_ARRIVED_THIS_WEEK_SUCCESS';
export const GET_ARRIVED_THIS_WEEK_ERROR = 'GET_ARRIVED_THIS_WEEK_ERROR';

export const GET_DASHBOARD_START = 'GET_DASHBOARD_START';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_ERROR = 'GET_DASHBOARD_ERROR';
